config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :featured_products
  end
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/featured_product.rb
class Spree::FeaturedProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :store
  delegate :images, to: :product
  delegate :name, to: :product, prefix: true
  delegate :variant_images, to: :product
  delegate :name, to: :store, prefix: true

  scope :by_store, -> (store_id) { where(store_id: store_id ) }

  scope :by_taxonomy, lambda { |name| joins(product: [taxons: :taxonomy]).where(spree_taxonomies: {name: name}) }

  validates :store_id, presence: true
end

app/controllers/spree/admin/featured_products_controller.rb
class Spree::Admin::FeaturedProductsController < Spree::Admin::ResourceController

  before_action :set_featured_product, only: [:show, :edit, :update, :destroy]
  before_action :load_stores, only: [:new, :edit, :update, :create]
  before_action :load_products_by_store, only: [:edit, :update]

  def index
    @featured_products = Spree::FeaturedProduct.all
  end

  def show
  end

  def new
    @featured_product = Spree::FeaturedProduct.new
    @products = Spree::Product.all
  end

  def edit
  end

  def create
    @featured_product = Spree::FeaturedProduct.new(featured_product_params)
    respond_to do |format|
      if @featured_product.save
        flash[:success] = Spree.t(:create, scope: [:featured_products])
        format.html { redirect_to spree.edit_admin_featured_product_path(@featured_product) }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @featured_product.update_attributes(featured_product_params)
        flash[:success] = Spree.t(:update, scope: [:featured_products])
        format.html { redirect_to spree.edit_admin_featured_product_path(@featured_product) }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def set_featured_product
    @featured_product = Spree::FeaturedProduct.find params[:id]
  end

  def load_stores
    @stores = Spree::Store.order(:name)
  end

  def load_products_by_store
    @products = Spree::Product.by_store(@featured_product.store_id)
  end

  def featured_product_params
    params.require(:featured_product).permit(:name, :product_id, :store_id)
  end
end

app/controllers/spree/home_controller_decorator.rb
module Spree
  HomeController.class_eval do
    before_action :set_featured_products, only: :landing

    private

    def set_featured_products
      @featured_products = Spree::FeaturedProduct.by_store(current_store.id)
    end
  end
end

app/views/partials/_featured_products_widget.html.erb
<div class="featured-products col-md-12 col-xs-12">
    <% @featured_products.each do |featured_product| %>
      <div class='col-md-3'>
        <% product = featured_product.product %>
        <%= link_to small_image(product, itemprop: 'image'), product, itemprop: 'url' %>
          <p>
            <%= product.name %>
          </p>
      </div>
    <% end %>
</div>

app/views/spree/admin/featured_products/_form.html.erb
<div data-hook="admin_featured_product_form_fields">
  <div data-hook="store" class="field align-center">
    <%= label_tag Spree.t(:store) %><br>
    <%= f.collection_select(:store_id, @stores, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2', data: { url: admin_products_path(format: :json) } }) %>
    <br>
    <% unless @featured_product.store_id.nil? %>
      <div data-hook="product" class="field align-center">
        <%= label_tag Spree.t(:product) %><br>
        <%= f.collection_select(:product_id, @products, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2' }) %>
      </div>
    <% end %>
  </div>
</div>

app/views/spree/admin/featured_products/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_featured_product) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_featured_products_list), spree.admin_featured_products_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @eatured_product } %>

<%= form_for [:admin, @featured_product] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/featured_products/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_featured_products) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_featured_product), new_admin_featured_product_path, :icon => 'icon-plus', :id => 'admin_new_featured_product' %>
  </li>
<% end if can? :edit, Spree::FeaturedProduct.new %>

<% if @featured_products.count != 0 %>
  <table>
    <thead>
      <tr>
        <th><%= Spree.t(:product) %></th>
        <th><%= Spree.t(:store) %></th>
        <th class='actions'></th>
      </tr>
    </thead>

    <tbody>
      <% @featured_products.each do |product| %>
        <tr>
          <td><%= product.product.name %></td>
          <td><%= product.store_name %></td>
          <td class='actions'>
            <%= link_to_edit product.id, no_text: true %>
            <%= link_to_delete product, no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: "featured items") %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_featured_product_path %>!
  </div>
<% end %>
<br>

app/views/spree/admin/featured_products/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:new_featured_product) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_featured_products_list), spree.admin_featured_products_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @featured_product } %>


<%= form_for [:admin, @featured_product] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>